// packages/vue/src/NepaliDatePicker.vue
<script setup>
/**
 * NepaliDatePicker.vue — Vue 3 Composition API
 * @universal-sambat-sdk/vue
 *
 * Usage:
 *   <NepaliDatePicker v-model="date" :options="{ theme: 'ocean-blue', lang: 'ne' }" />
 */
import { ref, onMounted, onUnmounted, watch } from 'vue';

const props = defineProps({
  modelValue:  { type: String,  default: '' },
  options:     { type: Object,  default: () => ({}) },
  placeholder: { type: String,  default: 'Select Nepali date' },
  disabled:    { type: Boolean, default: false },
  class:       { type: String,  default: '' },
});

const emit = defineEmits(['update:modelValue', 'change', 'range-change', 'open', 'close']);

const inputRef  = ref(null);
let   picker    = null;

onMounted(() => {
  if (!window.NepaliDatePicker) {
    console.error('[NepaliDatePicker Vue] Core library not found.');
    return;
  }

  picker = new window.NepaliDatePicker(inputRef.value, {
    ...props.options,
    onChange: (date) => {
      emit('update:modelValue', date?.formatted ?? '');
      emit('change', date);
      props.options.onChange?.(date);
    },
    onRangeChange: (start, end) => {
      emit('range-change', { start, end });
      props.options.onRangeChange?.(start, end);
    },
    onOpen:  () => emit('open'),
    onClose: () => emit('close'),
  });

  if (props.modelValue) picker.setDate(props.modelValue);
});

onUnmounted(() => picker?.destroy());

// Sync v-model changes from parent
watch(() => props.modelValue, (val) => {
  if (!picker) return;
  const current = picker.getDate();
  const currentStr = current?.formatted ?? '';
  if (val !== currentStr) {
    if (val) picker.setDate(val);
    else     picker.clear();
  }
});
</script>

<template>
  <input
    ref="inputRef"
    type="text"
    :placeholder="placeholder"
    :disabled="disabled"
    :class="['ndp-vue-input', $props.class]"
    :readonly="!options.autoMask"
  />
</template>

// packages/react/src/NepaliDatePicker.jsx
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';

/**
 * NepaliDatePicker — React component
 * Wraps the vanilla NepaliDatePicker library.
 *
 * Usage:
 *   import { NepaliDatePicker } from '@universal-sambat-sdk/react';
 *   <NepaliDatePicker value={date} onChange={setDate} options={{ theme: 'ocean-blue', lang: 'ne' }} />
 */
export const NepaliDatePicker = forwardRef(function NepaliDatePicker(
  {
    value      = '',
    onChange   = null,
    options    = {},
    placeholder = 'Select Nepali date',
    className  = '',
    style      = {},
    disabled   = false,
    ...rest
  },
  ref
) {
  const inputRef    = useRef(null);
  const pickerRef   = useRef(null);

  // Expose imperative API via ref
  useImperativeHandle(ref, () => ({
    open:     () => pickerRef.current?.open(),
    close:    () => pickerRef.current?.close(),
    clear:    () => pickerRef.current?.clear(),
    getDate:  () => pickerRef.current?.getDate(),
    setDate:  (d) => pickerRef.current?.setDate(d),
    getRange: () => pickerRef.current?.getRange(),
    setTheme: (t) => pickerRef.current?.setTheme(t),
    setLang:  (l) => pickerRef.current?.setLang(l),
    jumpTo:   (y, m) => pickerRef.current?.jumpTo(y, m),
    destroy:  () => pickerRef.current?.destroy(),
  }));

  useEffect(() => {
    const Ctor = window?.NepaliDatePicker;
    if (!Ctor) {
      console.error('[NepaliDatePicker] Core library not found. Include dist/nepali-datepicker.js.');
      return;
    }

    const mergedOptions = {
      ...options,
      onChange: (date) => {
        onChange?.(date);
        options.onChange?.(date);
      },
      onRangeChange: (start, end) => {
        options.onRangeChange?.(start, end);
      },
    };

    pickerRef.current = new Ctor(inputRef.current, mergedOptions);
    if (value) pickerRef.current.setDate(value);

    return () => pickerRef.current?.destroy();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Sync controlled value
  useEffect(() => {
    if (!pickerRef.current) return;
    const current = pickerRef.current.getDate();
    const currentStr = current ? current.formatted ?? '' : '';
    if (value !== currentStr) {
      if (value) pickerRef.current.setDate(value);
      else pickerRef.current.clear();
    }
  }, [value]);

  return (
    <input
      ref={inputRef}
      type="text"
      placeholder={placeholder}
      className={['ndp-react-input', className].filter(Boolean).join(' ')}
      style={style}
      disabled={disabled}
      readOnly={!options.autoMask}
      {...rest}
    />
  );
});

export default NepaliDatePicker;
