// src/svelte/NepaliDatePicker.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  // Expose component props
  export let value = '';
  export let options = {};
  export let placeholder = 'Select Nepali Date';
  export let className = '';
  export let style = {};
  export let disabled = false;

  let inputEl;
  let pickerInstance = null;

  onMount(() => {
    if (!window.NepaliDatePicker) {
      console.warn('NepaliDatePicker: Core library not found. Ensure dist/nepali-datepicker.js is loaded.');
      return;
    }

    // Merge options and bind custom callback events
    const mergedOptions = {
      ...options,
      onChange: (date) => {
        value = date ? date.formatted : '';
        dispatch('change', date);
        if (options.onChange) options.onChange(date);
      },
      onRangeChange: (start, end) => {
        dispatch('rangeChange', { start, end });
        if (options.onRangeChange) options.options.onRangeChange(start, end);
      }
    };

    if (inputEl) {
      pickerInstance = new window.NepaliDatePicker(inputEl, mergedOptions);
      if (value) {
        pickerInstance.setDate(value);
      }
    }
  });

  // Watch value updates reactively in Svelte
  $: if (pickerInstance && value) {
    const currentVal = pickerInstance.getDate();
    const currentValStr = currentVal ? currentVal.formatted : '';
    if (value !== currentValStr && value !== inputEl.value) {
      pickerInstance.setDate(value);
    }
  }

  onDestroy(() => {
    if (pickerInstance) {
      pickerInstance.destroy();
    }
  });
</script>

<input
  bind:this={inputEl}
  type="text"
  {placeholder}
  class="nepali-datepicker-input {className}"
  style={Object.entries(style).map(([k, v]) => `${k}:${v}`).join(';')}
  {disabled}
  readonly={!options.autoMask}
  {...$$restProps}
/>

// src/react/NepaliDatePicker.jsx
import React, { useEffect, useRef } from 'react';
import PropTypes from 'prop-types';

/**
 * React Wrapper Component for Nepali DatePicker Studio
 * Allows seamless integration into React/Vite/Next.js frameworks.
 */
export const NepaliDatePicker = ({
  options = {},
  value = '',
  onChange = () => {},
  placeholder = 'Select Nepali Date',
  className = '',
  style = {},
  disabled = false,
  ...props
}) => {
  const inputRef = useRef(null);
  const pickerInstance = useRef(null);

  useEffect(() => {
    // Check if the underlying vanilla script is loaded globally
    if (!window.NepaliDatePicker) {
      console.warn('NepaliDatePicker: Core library not found. Ensure dist/nepali-datepicker.js is included in your application.');
      return;
    }

    // Merge options and bind custom component callback
    const mergedOptions = {
      ...options,
      onChange: (date) => {
        onChange(date);
        if (options.onChange) options.onChange(date);
      }
    };

    if (inputRef.current) {
      // Instantiate native datepicker
      pickerInstance.current = new window.NepaliDatePicker(inputRef.current, mergedOptions);
      
      if (value) {
        pickerInstance.current.setDate(value);
      }
    }

    // Cleanup instance on component unmount
    return () => {
      if (pickerInstance.current) {
        pickerInstance.current.destroy();
      }
    };
  }, []);

  // Sync datepicker value updates reactively
  useEffect(() => {
    if (pickerInstance.current && value) {
      const currentVal = pickerInstance.current.getDate();
      const currentValStr = currentVal ? currentVal.formatted : '';
      if (value !== currentValStr && value !== inputRef.current.value) {
        pickerInstance.current.setDate(value);
      }
    }
  }, [value]);

  return (
    <input
      type="text"
      ref={inputRef}
      placeholder={placeholder}
      className={`nepali-datepicker-input ${className}`}
      style={style}
      disabled={disabled}
      readOnly={!options.autoMask}
      {...props}
    />
  );
};

NepaliDatePicker.propTypes = {
  options: PropTypes.object,
  value: PropTypes.string,
  onChange: PropTypes.func,
  placeholder: PropTypes.string,
  className: PropTypes.string,
  style: PropTypes.object,
  disabled: PropTypes.bool
};

export default NepaliDatePicker;
